name: pay_buttons
description: "A cross-platform Flutter package providing beautiful, accessible payment buttons for modern e-commerce checkouts."
version: 0.1.0
homepage: https://github.com/Robert-SD/pay_buttons
repository: https://github.com/Robert-SD/pay_buttons
issue_tracker: https://github.com/Robert-SD/pay_buttons/issues

topics:
  - payments
  - checkout
  - buttons
  - ecommerce
  - ui

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.13.4
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
